source 'https://rubygems.org'

gem 'rake', '~>10.4'
gem 'serverspec', '~>2.7'
gem 'aws-sdk', '~>1.61'
gem 'vagrant_cloud', '~>0.4'
gem 'rspec-core', '~>3.1'
gem 'librarian-puppet', '~>2.0'
gem 'puppet', '~>3.7'
gem 'komenda', '~>0.0.4'
