mod 'cargomedia/cm',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/cm'

mod 'cargomedia/janus',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/janus'
