if RUBY_PLATFORM[/linux/] then
	bridge_interface = "ra0"
else
	bridge_interface = "en1: Wi-Fi (AirPort)"
end

Vagrant.configure("2") do |config|
	config.vm.box = "debian-7.1-amd64"
	config.vm.box_url = "debian-7.1-amd64.box"
	config.vm.hostname = "debian-7.1-amd64"
	config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", 1024]
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	end

	config.vm.synced_folder "~/Desktop", "/home/vagrant/desktop", nfs: true
	config.vm.network :private_network, ip: "10.10.10.20"
end